blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/OWNER/REPO/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“š Documentation
    url: https://github.com/OWNER/REPO/wiki
    about: Check the documentation for answers

